---
# Source: shared-resources/templates/ingress-4bf038c0ef8088868c1888c12c74eec59da04167-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 4bf038c0ef8088868c1888c12c74eec59da04167-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: jaytest101.development.evk8sbswc11.cmp.test.bs.ch
    http:
      paths:
      - backend:
          service:
            name: jaytest101
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - jaytest101.development.evk8sbswc11.cmp.test.bs.ch
    secretName: defunct
