---
# Source: default-module/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: whatever-workload
  labels:
    
    helm.sh/chart: default-module-1.16.11
    
    app.kubernetes.io/name: "whatever-workload"
    app.kubernetes.io/instance: "whatever-workload"
    app.kubernetes.io/managed-by: "Helm"
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      name: port-default
  selector:
    
    app.kubernetes.io/name: "whatever-workload"
    app.kubernetes.io/instance: "whatever-workload"
